# Generated by Django 4.2.7 on 2025-10-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False, verbose_name='通知ID')),
                ('notification_type', models.CharField(choices=[('system_announcement', '系统公告'), ('system_maintenance', '系统维护通知'), ('account_activated', '账号激活'), ('password_changed', '密码修改'), ('position_published', '新岗位发布'), ('position_updated', '岗位信息更新'), ('position_closed', '岗位关闭'), ('position_deadline_soon', '申请截止提醒'), ('application_submitted', '收到新申请'), ('application_reviewing', '申请审核中'), ('application_accepted', '申请通过'), ('application_rejected', '申请被拒'), ('application_withdrawn', '申请已撤回'), ('timesheet_submitted', '收到工时表'), ('timesheet_approved', '工时已批准'), ('timesheet_rejected', '工时被驳回'), ('timesheet_reminder', '工时提交提醒'), ('salary_generated', '薪酬已生成'), ('salary_paid', '薪酬已发放'), ('salary_delayed', '薪酬延迟通知'), ('role_granted', '角色授予'), ('role_revoked', '角色撤销'), ('became_ta', '成为助教'), ('evaluation_received', '收到工作评价'), ('evaluation_reminder', '评价提醒')], max_length=50, verbose_name='通知类型')),
                ('category', models.CharField(choices=[('system', '系统通知'), ('application', '申请相关'), ('timesheet', '工时相关'), ('salary', '薪酬相关')], max_length=20, verbose_name='通知分类')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=10, verbose_name='优先级')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('related_model', models.CharField(blank=True, help_text='如: Application, Timesheet, Position', max_length=50, null=True, verbose_name='关联模型')),
                ('related_object_id', models.IntegerField(blank=True, null=True, verbose_name='关联对象ID')),
                ('expires_at', models.DateTimeField(blank=True, help_text='重要通知不过期（NULL）', null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(blank=True, help_text='系统通知时为NULL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_201701_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f8d066_idx'), models.Index(fields=['category'], name='notificatio_categor_98adff_idx'), models.Index(fields=['created_at'], name='notificatio_created_db7ad3_idx')],
            },
        ),
    ]
