# Generated by Django 4.2.7 on 2025-10-15 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('timesheet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='工时表ID')),
                ('month', models.DateField(help_text='存储月初日期，如: 2025-03-01', verbose_name='工作月份')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(744)], verbose_name='工作小时数')),
                ('work_description', models.TextField(verbose_name='工作描述')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='recruitment.position', verbose_name='岗位')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_timesheets', to=settings.AUTH_USER_MODEL, verbose_name='审核教师')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to=settings.AUTH_USER_MODEL, verbose_name='助教')),
            ],
            options={
                'verbose_name': '工时表',
                'verbose_name_plural': '工时表',
                'db_table': 'timesheet',
                'ordering': ['-month', '-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False, verbose_name='薪酬ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='薪酬金额（元）')),
                ('calculation_details', models.JSONField(blank=True, help_text='JSON格式存储计算过程，如: {"hours":40.5, "rate":50, "formula":"40.5×50"}', null=True, verbose_name='计算明细')),
                ('payment_status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付')], default='pending', max_length=20, verbose_name='支付状态')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='报表生成时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('payment_method', models.CharField(blank=True, help_text='如: 银行转账, 支付宝', max_length=50, null=True, verbose_name='支付方式')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='交易流水号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_salaries', to=settings.AUTH_USER_MODEL, verbose_name='报表生成人（管理员）')),
                ('timesheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='timesheet.timesheet', verbose_name='关联工时表')),
            ],
            options={
                'verbose_name': '薪酬记录',
                'verbose_name_plural': '薪酬记录',
                'db_table': 'salary',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['ta'], name='timesheet_ta_id_70580c_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['position'], name='timesheet_positio_78bd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['status'], name='timesheet_status_892dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='timesheet',
            index=models.Index(fields=['month'], name='timesheet_month_afb741_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timesheet',
            unique_together={('ta', 'position', 'month')},
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['payment_status'], name='salary_payment_f2324a_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['generated_by'], name='salary_generat_3055a0_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['generated_at'], name='salary_generat_ec8e92_idx'),
        ),
    ]
