# Generated by Django 4.2.7 on 2025-10-15 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False, verbose_name='申请ID')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('reviewing', '审核中'), ('accepted', '已录用'), ('rejected', '已拒绝')], default='submitted', max_length=20, verbose_name='申请状态')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='简历文件')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='审核备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.position', verbose_name='申请的岗位')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '申请记录',
                'verbose_name_plural': '申请记录',
                'db_table': 'application',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['applicant'], name='application_applica_715029_idx'), models.Index(fields=['status'], name='application_status_b7b725_idx'), models.Index(fields=['applied_at'], name='application_applied_6434a1_idx')],
                'unique_together': {('position', 'applicant')},
            },
        ),
    ]
