# Generated by Django 4.2.7 on 2025-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="resume_text",
            field=models.TextField(blank=True, null=True, verbose_name="在线填写简历"),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/%Y/%m/",
                verbose_name="简历文件",
            ),
        ),
    ]
