# Generated by Django 4.2.7 on 2025-10-15 09:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_id', models.AutoField(primary_key=True, serialize=False, verbose_name='岗位ID')),
                ('title', models.CharField(max_length=200, verbose_name='岗位标题')),
                ('course_name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('course_code', models.CharField(max_length=20, verbose_name='课程代码')),
                ('description', models.TextField(verbose_name='岗位描述')),
                ('requirements', models.TextField(verbose_name='任职要求')),
                ('num_positions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='招聘人数')),
                ('num_filled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='已录用人数')),
                ('work_hours_per_week', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='每周工时')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='时薪（元/小时）')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('application_deadline', models.DateTimeField(verbose_name='申请截止时间')),
                ('status', models.CharField(choices=[('open', '开放中'), ('closed', '已关闭'), ('filled', '已招满')], default='open', max_length=20, verbose_name='岗位状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posted_positions', to=settings.AUTH_USER_MODEL, verbose_name='发布教师')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'position',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='position_status_62178f_idx'), models.Index(fields=['posted_by'], name='position_posted__1edb08_idx'), models.Index(fields=['course_code'], name='position_course__1d1df1_idx'), models.Index(fields=['application_deadline'], name='position_applica_d5faca_idx')],
            },
        ),
    ]
